### PR TITLE
Ft models and migrations 149366719

### PR DESCRIPTION
**Pull request by mkiterian**
Created data models and migrated them to the database

### CODE REVIEW

**Comment by iankigen** [comment]
good naming convention

**Comment by Thuku** [comment]
You are practicing good git workflow in naming your branches and commits. Good work.  You can take a look on how to create a PR on Andela's best practices.

**Comment by mkiterian** [comment]
I'll review and implement the Andela Pull request best practrices

**Comment by HawiCaesar** [comment]
Good work flow and naming convention. As @Thuku has said, take a look at the Andela best practices. It has a few good tips on doing PR's.

**Pull request merged**
